/*
 * Copyright (C) 2024-2026 DBSutra. All rights reserved.
 * Licensed under the GNU Affero General Public License v3.0 (AGPL-3.0).
 * See LICENSE file in the project root for full license information.
 */
import type { Theme } from '@core/types'

// ── ThemeDBRow interface ───────────────────────────────────────────────
export interface ThemeDBRow {
  id: string
  name: string
  colors: Record<string, string>
  isBuiltin: boolean
}

// ── Dark theme ─────────────────────────────────────────────────────────
const DARK_THEME: Theme = {
  id: 'dark',
  name: 'Dark (Default)',
  colors: {
    '--color-bg-primary':       '#1a1a1a',
    '--color-bg-secondary':     '#262626',
    '--color-bg-tertiary':      '#2a2a2a',
    '--color-bg-active':        '#333333',
    '--color-bg-hover':         '#2f2f2f',
    '--color-bg-input':         '#333333',
    '--color-bg-panel':         '#282828',
    '--color-bg-surface':       '#1e1e1e',
    '--color-border':           '#3a3a3a',
    '--color-border-subtle':    '#2e2e2e',
    '--color-text-primary':     '#eff1f6',
    '--color-text-secondary':   '#a3a3a3',
    '--color-text-muted':       '#5c5c5c',
    '--color-accent':           '#2cbb5d',
    '--color-accent-hover':     '#36d068',
    '--color-accent-light':     'rgba(44, 187, 93, 0.12)',
    '--color-accent-blue':      '#4d90fe',
    '--color-accent-orange':    '#ffa116',
    '--color-activitybar-bg':   '#1a1a1a',
    '--color-activitybar-fg':   '#5c5c5c',
    '--color-activitybar-active-fg': '#eff1f6',
    '--color-activitybar-hover-bg':  '#262626',
    '--color-sidebar-bg':       '#282828',
    '--color-tab-bg':           'transparent',
    '--color-tab-active-bg':    '#282828',
    '--color-tab-hover-bg':     '#333333',
    '--color-statusbar-bg':     '#262626',
    '--color-statusbar-fg':     '#a3a3a3',
    '--color-editor-bg':        '#1a1a1a',
    '--color-success':          '#2cbb5d',
    '--color-error':            '#ef4743',
    '--color-warning':          '#ffa116',
    '--color-scrollbar-thumb':  'rgba(255, 255, 255, 0.1)',
    '--color-scrollbar-hover':  'rgba(255, 255, 255, 0.18)',
    '--color-bg-hover-subtle':  'rgba(255, 255, 255, 0.04)',
    '--color-bg-active-subtle': 'rgba(255, 255, 255, 0.08)',
    '--color-bg-editor':        '#1e1e1e',
    '--color-bg-tabbar':        '#282828',
    '--color-bg-tab-inactive':  'transparent',
    '--color-bg-tab-active':    '#282828',
    '--color-success-subtle':   'rgba(44, 187, 93, 0.1)',
    '--color-success-glow':     'rgba(44, 187, 93, 0.4)',
    '--color-error-subtle':     'rgba(239, 71, 67, 0.08)',
    '--color-error-border':     'rgba(239, 71, 67, 0.3)',
    '--color-error-hover':      '#d93c3a',
    '--color-null-text':        'rgba(163, 163, 163, 0.5)',
    '--color-pk-icon':          '#dbb851',
    '--color-shadow-sm':        'rgba(0, 0, 0, 0.3)',
    '--color-shadow-md':        'rgba(0, 0, 0, 0.35)',
    '--color-shadow-lg':        'rgba(0, 0, 0, 0.5)',
    '--color-shadow-panel':     'rgba(0, 0, 0, 0.2)',
    '--color-shadow-float':     'rgba(0, 0, 0, 0.6)',
    '--color-db-mysql':         '#e48e00',
    '--color-db-postgres':      '#336791',
    '--color-db-mongo':         '#4db33d',
  },
  components: {},
}

// ── Light theme ────────────────────────────────────────────────────────
const LIGHT_THEME: Theme = {
  id: 'light',
  name: 'Light',
  colors: {
    '--color-bg-primary':       '#fafafa',
    '--color-bg-secondary':     '#f0f0f0',
    '--color-bg-tertiary':      '#e8e8e8',
    '--color-bg-active':        '#e0e0e0',
    '--color-bg-hover':         '#ebebeb',
    '--color-bg-input':         '#ffffff',
    '--color-bg-panel':         '#ffffff',
    '--color-bg-surface':       '#fafafa',
    '--color-border':           '#e0e0e0',
    '--color-border-subtle':    '#ececec',
    '--color-text-primary':     '#1f1f1f',
    '--color-text-secondary':   '#555555',
    '--color-text-muted':       '#999999',
    '--color-accent':           '#2cbb5d',
    '--color-accent-hover':     '#259e4e',
    '--color-accent-light':     'rgba(44, 187, 93, 0.1)',
    '--color-accent-blue':      '#3b78e7',
    '--color-accent-orange':    '#e69500',
    '--color-activitybar-bg':   '#fafafa',
    '--color-activitybar-fg':   '#999999',
    '--color-activitybar-active-fg': '#1f1f1f',
    '--color-activitybar-hover-bg':  '#f0f0f0',
    '--color-sidebar-bg':       '#ffffff',
    '--color-tab-bg':           'transparent',
    '--color-tab-active-bg':    '#ffffff',
    '--color-tab-hover-bg':     '#f0f0f0',
    '--color-statusbar-bg':     '#f0f0f0',
    '--color-statusbar-fg':     '#555555',
    '--color-editor-bg':        '#ffffff',
    '--color-success':          '#2cbb5d',
    '--color-error':            '#e53935',
    '--color-warning':          '#e69500',
    '--color-scrollbar-thumb':  'rgba(0, 0, 0, 0.15)',
    '--color-scrollbar-hover':  'rgba(0, 0, 0, 0.25)',
    '--color-bg-hover-subtle':  'rgba(0, 0, 0, 0.04)',
    '--color-bg-active-subtle': 'rgba(0, 0, 0, 0.08)',
    '--color-bg-editor':        '#fafafa',
    '--color-bg-tabbar':        '#ffffff',
    '--color-bg-tab-inactive':  'transparent',
    '--color-bg-tab-active':    '#ffffff',
    '--color-success-subtle':   'rgba(44, 187, 93, 0.1)',
    '--color-success-glow':     'rgba(44, 187, 93, 0.4)',
    '--color-error-subtle':     'rgba(229, 57, 53, 0.08)',
    '--color-error-border':     'rgba(229, 57, 53, 0.3)',
    '--color-error-hover':      '#c62828',
    '--color-null-text':        'rgba(85, 85, 85, 0.5)',
    '--color-pk-icon':          '#b8942b',
    '--color-shadow-sm':        'rgba(0, 0, 0, 0.05)',
    '--color-shadow-md':        'rgba(0, 0, 0, 0.1)',
    '--color-shadow-lg':        'rgba(0, 0, 0, 0.15)',
    '--color-shadow-panel':     'rgba(0, 0, 0, 0.05)',
    '--color-shadow-float':     'rgba(0, 0, 0, 0.2)',
    '--color-db-mysql':         '#e48e00',
    '--color-db-postgres':      '#336791',
    '--color-db-mongo':         '#4db33d',
  },
  components: {},
}

// ── Built-in themes array ──────────────────────────────────────────────
export const BUILTIN_THEMES: Theme[] = [DARK_THEME, LIGHT_THEME]
